{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install trimesh -quite"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install git+https://github.com/CadQuery/cadquery.git -quite"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install reportlab -quite"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install python-occ -quite"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Documentation Related Libraries\n",
    "import os\n",
    "import glob\n",
    "import numpy as np\n",
    "from reportlab.lib.pagesizes import letter\n",
    "from reportlab.pdfgen import canvas\n",
    "from reportlab.lib.styles import getSampleStyleSheet\n",
    "from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer\n",
    "from reportlab.lib.utils import simpleSplit\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Feature Extraction Libraries\n",
    "import cadquery as cq\n",
    "from cadquery import exporters\n",
    "import trimesh as tm\n",
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# OCC Related Libraries\n",
    "from OCC.Core.STEPControl import STEPControl_Reader\n",
    "from OCC.Core.TopoDS import topods\n",
    "from OCC.Core.BRepAdaptor import BRepAdaptor_Curve\n",
    "from OCC.Core.GeomAbs import GeomAbs_Circle\n",
    "from OCC.Core.TopExp import TopExp_Explorer\n",
    "from OCC.Core.GeomAbs import GeomAbs_Line, GeomAbs_Circle, GeomAbs_Ellipse, GeomAbs_Hyperbola, GeomAbs_Parabola, GeomAbs_BSplineCurve, GeomAbs_BezierCurve\n",
    "from OCC.Core.TopAbs import TopAbs_EDGE\n",
    "from collections import defaultdict\n",
    "from OCC.Extend.DataExchange import read_step_file\n",
    "from OCC.Core.GProp import GProp_GProps\n",
    "from OCC.Core.Interface import Interface_Static"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Initialise pdf storage folder\n",
    "\n",
    "# The path under directory_PDF is the path to save the generated PDF.\n",
    "directory_PDF = \"D:\\VSCODE\\paper_code\\PDF\"\n",
    "\n",
    "# Build a path pattern that searches all files\n",
    "all_files_pattern_PDF = os.path.join(directory_PDF, \"*\")\n",
    "\n",
    "# Get a list of all files in a directory\n",
    "all_files_PDF = glob.glob(all_files_pattern_PDF)\n",
    "\n",
    "for file in all_files_PDF:\n",
    "    try:\n",
    "        os.remove(file)\n",
    "        print(f\"Deleted documents: {file}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error when deleting a file: {file}, error: {e}\")\n",
    "\n",
    "\n",
    "# Initialise edges step storage folder\n",
    "# directory_edges is the address where the generated step files are stored locally\n",
    "directory_edges = \"D:\\VSCODE\\paper_code\\edges_step\"\n",
    "\n",
    "# Build a path pattern that searches all files\n",
    "all_files_pattern_edges = os.path.join(directory_edges, \"*\")\n",
    "\n",
    "# Get a list of all files in a directory\n",
    "all_files_edges = glob.glob(all_files_pattern_edges)\n",
    "\n",
    "for file in all_files_edges:\n",
    "    try:\n",
    "        os.remove(file)\n",
    "        print(f\"Deleted documents: {file}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error when deleting a file: {file}, error: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def analyze_holes(shape, tolerance=1e-7):\n",
    "    \"\"\"\n",
    "    Analysing rounded edges in shapes and calculating their diameters and quantities\n",
    "    \n",
    "    parameters:\n",
    "    shape - Shape to be analysed\n",
    "    \n",
    "    return:\n",
    "    circle_data - DataFrame containing the diameter\n",
    "    circle_count - Number of rounded edges\n",
    "    \"\"\"\n",
    "    edge_explorer = TopExp_Explorer(shape, TopAbs_EDGE)\n",
    "    circular_edges_by_center = defaultdict(list)\n",
    "\n",
    "    while edge_explorer.More():\n",
    "        edge = topods.Edge(edge_explorer.Current())\n",
    "        curve_adaptor = BRepAdaptor_Curve(edge)\n",
    "        \n",
    "        if curve_adaptor.GetType() == GeomAbs_Circle:\n",
    "            circ = curve_adaptor.Circle()\n",
    "            radius = circ.Radius()\n",
    "            center = circ.Location()\n",
    "            p1 = curve_adaptor.Value(curve_adaptor.FirstParameter())\n",
    "            p2 = curve_adaptor.Value(curve_adaptor.LastParameter())\n",
    "            if p1.IsEqual(p2, 1e-7):  # Check that the sides are closed\n",
    "                circular_edges_by_center[(center.X(), center.Y(), center.Z())].append(radius)\n",
    "        \n",
    "        edge_explorer.Next()\n",
    "\n",
    "    # Filter out the smallest diameter circle at each centre\n",
    "    unique_circular_edges = []\n",
    "    unique_centers = []\n",
    "    for center, radii in circular_edges_by_center.items():\n",
    "        min_radius = min(radii)\n",
    "        unique_circular_edges.append(min_radius)\n",
    "        unique_centers.append(center)\n",
    "\n",
    "    # Check coaxial condition and filter\n",
    "    def is_collinear(c1, c2, tol):\n",
    "        # Check that two circle centres have the same coordinates and only one is different (tolerate errors)\n",
    "        count = sum(1 for a, b in zip(c1, c2) if abs(a - b) <= tol)\n",
    "        return count == 2\n",
    "    \n",
    "    collinear_groups = defaultdict(list)\n",
    "    for i, center1 in enumerate(unique_centers):\n",
    "        for j, center2 in enumerate(unique_centers):\n",
    "            if i != j and is_collinear(center1, center2, tolerance):\n",
    "                collinear_groups[i].append(center1)\n",
    "                collinear_groups[i].append(center2)\n",
    "\n",
    "    # Delete the middle centre of an odd number of coaxial circles\n",
    "    for key in collinear_groups.keys():\n",
    "        group = list(set(collinear_groups[key]))  # weight removal\n",
    "        if len(group) % 2 != 0:\n",
    "            group.sort()  # Sorting to remove intermediate values\n",
    "            middle_index = len(group) // 2\n",
    "            group.pop(middle_index)  # Delete the centre of the middle circle\n",
    "        collinear_groups[key] = group\n",
    "\n",
    "    valid_centers = set()\n",
    "    for centers in collinear_groups.values():\n",
    "        valid_centers.update(centers)\n",
    "\n",
    "    filtered_edges = []\n",
    "    filtered_centers = []\n",
    "    for center, radius in zip(unique_centers, unique_circular_edges):\n",
    "        if center in valid_centers:\n",
    "            filtered_edges.append(radius)\n",
    "            filtered_centers.append(center)\n",
    "\n",
    "    # Calculate the number and diameter of circles\n",
    "    circle_count = len(filtered_edges) // 2  # Calculate the number of circles and round to the nearest whole number\n",
    "    circle_diameters = [2 * radius for radius in filtered_edges]\n",
    "\n",
    "    circle_data = pd.DataFrame({'Diameter': circle_diameters})\n",
    "\n",
    "    return circle_data, circle_count, filtered_edges, filtered_centers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def group_collinear_centers(filtered_centers, tolerance=1e-7):\n",
    "    \"\"\"\n",
    "    Divide the coaxial centres into groups of up to two centres each.\n",
    "    \n",
    "    parameters:\n",
    "    filtered_centers - List of centres to be grouped\n",
    "    tolerance - Tolerance error in determining coaxial\n",
    "    \n",
    "    return:\n",
    "    collinear_groups - Grouping of coaxial centres, each group containing up to two centres\n",
    "    \"\"\"\n",
    "    def is_collinear(c1, c2, tol):\n",
    "        # Check that two circle centres have the same coordinates and only one is different (tolerate errors)\n",
    "        count = sum(1 for a, b in zip(c1, c2) if abs(a - b) <= tol)\n",
    "        return count == 2\n",
    "\n",
    "    remaining_centers = set(filtered_centers)\n",
    "    collinear_groups = []\n",
    "    \n",
    "    while remaining_centers:\n",
    "        center1 = remaining_centers.pop()\n",
    "        group = [center1]\n",
    "        \n",
    "        for center2 in list(remaining_centers):\n",
    "            if is_collinear(center1, center2, tolerance):\n",
    "                group.append(center2)\n",
    "                remaining_centers.remove(center2)\n",
    "                break  # Exit the inner loop when you find a coaxial centre.\n",
    "        \n",
    "        if len(group) > 1:  # Only groups containing two circle centres are added to the result\n",
    "            collinear_groups.append(group)\n",
    "    \n",
    "    return collinear_groups\n",
    "\n",
    "def calculate_axis_directions_and_relationships(collinear_groups, tolerance=1e-7):\n",
    "    \"\"\"\n",
    "    Calculate the direction of the axes of each set of coaxial \n",
    "    centres and detect the parallel and perpendicular relationship between the axes\n",
    "    \n",
    "    parameters:\n",
    "    collinear_groups - List of coaxial centres for each group\n",
    "    tolerance - Tolerance errors in determining parallelism and perpendicularity\n",
    "    \n",
    "    return:\n",
    "    axis_directions - List of axis directions for each set of coaxial centres\n",
    "    parallel_count - Number of parallel axes\n",
    "    perpendicular_count - Number of vertical axes\n",
    "    \"\"\"\n",
    "    axis_directions = []\n",
    "    parallel_count = 0\n",
    "    perpendicular_count = 0\n",
    "\n",
    "    # Calculate the axis direction for each group\n",
    "    for group in collinear_groups:\n",
    "        if len(group) == 2:  # Make sure each group has two centres of the circle\n",
    "            center1, center2 = group\n",
    "            direction_vector = np.array(center2) - np.array(center1)\n",
    "            norm = np.linalg.norm(direction_vector)\n",
    "            if norm != 0:\n",
    "                direction_vector /= norm  # Normalised direction vector\n",
    "            axis_directions.append(direction_vector)\n",
    "    \n",
    "    # Detecting parallel and perpendicular relationships between axes\n",
    "    i = 0\n",
    "    while i < len(axis_directions):\n",
    "        direction_i = axis_directions[i]\n",
    "        detected = False\n",
    "        for j in range(i + 1, len(axis_directions)):\n",
    "            direction_j = axis_directions[j]\n",
    "            dot_product = np.dot(direction_i, direction_j)\n",
    "            if np.abs(dot_product - 1) <= tolerance or np.abs(dot_product + 1) <= tolerance:\n",
    "                parallel_count += 1\n",
    "                detected = True\n",
    "                break\n",
    "            elif np.abs(dot_product) <= tolerance:\n",
    "                perpendicular_count += 1\n",
    "                detected = True\n",
    "                break\n",
    "        if detected:\n",
    "            # Once a parallel or perpendicular relationship is detected, the current axis is removed and the test is repeated from the beginning.\n",
    "            axis_directions.pop(i)\n",
    "        else:\n",
    "            i += 1\n",
    "    \n",
    "    return axis_directions, parallel_count, perpendicular_count"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def classify_edges_in_shape(shape):\n",
    "    \"\"\"\n",
    "    Classify the edges in a shape as straight and curved and count the number of edges of each type\n",
    "    \n",
    "    parameters:\n",
    "    shape - Shape to be analysed\n",
    "    \n",
    "    return:\n",
    "    straight_edge_count - Number of straight edges\n",
    "    curved_edge_count - Number of curved edges\n",
    "    \"\"\"\n",
    "    straight_edge_count = 0\n",
    "    curved_edge_count = 0\n",
    "\n",
    "    # Iterate over all edges of the model\n",
    "    edge_explorer = TopExp_Explorer(shape, TopAbs_EDGE)\n",
    "    while edge_explorer.More():\n",
    "        edge = topods.Edge(edge_explorer.Current())\n",
    "        curve_adaptor = BRepAdaptor_Curve(edge)\n",
    "        \n",
    "        # Classification according to geometric type\n",
    "        curve_type = curve_adaptor.GetType()\n",
    "        if curve_type == GeomAbs_Line:\n",
    "            straight_edge_count += 1\n",
    "        else:\n",
    "            curved_edge_count += 1\n",
    "        \n",
    "        edge_explorer.Next()\n",
    "    \n",
    "    straight_edge_per = straight_edge_count/(straight_edge_count + curved_edge_count) *100\n",
    "    curved_edge_per = curved_edge_count/(straight_edge_count + curved_edge_count) *100\n",
    "\n",
    "    return straight_edge_per, curved_edge_per"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def determine_symmetry(mesh):\n",
    "    \"\"\"\n",
    "    Determine the symmetry description and symmetry axis/point based on the mesh's symmetry type.\n",
    "\n",
    "    Parameters:\n",
    "    mesh (object): The mesh object containing symmetry information.\n",
    "\n",
    "    Returns:\n",
    "    tuple: A tuple containing symmetry description (str) and symmetry axis/point (str or None).\n",
    "    \"\"\"\n",
    "    symmetry = mesh.symmetry\n",
    "    \n",
    "    if symmetry is None:\n",
    "        symmetry_description = \"This model_{first_8_chars} has no symmetry.\"\n",
    "        symmetry_axis = \"None\"\n",
    "    elif symmetry == \"radial\":\n",
    "        symmetry_description = \"This model_{first_8_chars} is radially symmetrical.\"\n",
    "        symmetry_axis = mesh.symmetry_axis\n",
    "    elif symmetry == \"spherical\":\n",
    "        symmetry_description = \"This model_{first_8_chars} is spherically symmetrical.\"\n",
    "        symmetry_axis = mesh.symmetry_axis\n",
    "    else:\n",
    "        symmetry_description = \"Unknown symmetry type.\"\n",
    "        symmetry_axis = \"Unknown\"\n",
    "    \n",
    "    return symmetry_description, symmetry_axis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CAD model design history information extraction\n",
    "def parse_json_to_sequence(json_file, model_name):\n",
    "    with open(json_file, 'r') as file:\n",
    "        data = json.load(file)\n",
    "    \n",
    "    entities = data['entities']\n",
    "    sequence = data['sequence']\n",
    "    \n",
    "    commands = []\n",
    "    descriptions = []\n",
    "    \n",
    "    for step in sequence:\n",
    "        entity = entities[step['entity']]\n",
    "        if step['type'] == 'Sketch':\n",
    "            command, description = parse_sketch(entity, model_name)\n",
    "        elif step['type'] == 'ExtrudeFeature':\n",
    "            command, description = parse_extrude(entity, model_name)\n",
    "        commands.append(command)\n",
    "        descriptions.append(description)\n",
    "    \n",
    "    return '\\n'.join(commands), '\\n'.join(descriptions)\n",
    "\n",
    "def parse_sketch(entity, model_name):\n",
    "    name = entity['name']\n",
    "    \n",
    "    sketch_commands = [f\"{name}\"]\n",
    "    sketch_descriptions = [f\"{model_name} creates a sketch named {name} with the following features:\"]\n",
    "    \n",
    "    for profile_key, profile_value in entity['profiles'].items():\n",
    "        loops = profile_value['loops']\n",
    "        for loop in loops:\n",
    "            profile_curves = loop['profile_curves']\n",
    "            for curve in profile_curves:\n",
    "                if curve['type'] == 'Circle3D':\n",
    "                    x = curve['center_point']['x']\n",
    "                    y = curve['center_point']['y']\n",
    "                    r = curve['radius']\n",
    "                    sketch_commands.append(f\"R ({x}, {y}, {r})\")\n",
    "                    sketch_descriptions.append(f\"{model_name} creates a circle centered at ({x}, {y}) with radius {r}.\")\n",
    "                elif curve['type'] == 'Line3D':\n",
    "                    x = curve['end_point']['x']\n",
    "                    y = curve['end_point']['y']\n",
    "                    sketch_commands.append(f\"L ({x}, {y})\")\n",
    "                    sketch_descriptions.append(f\"{model_name} creates a line ending at ({x}, {y}).\")\n",
    "                elif curve['type'] == 'Arc3D':\n",
    "                    x = curve['end_point']['x']\n",
    "                    y = curve['end_point']['y']\n",
    "                    alpha = curve.get('sweep_angle', 0)\n",
    "                    f = curve.get('is_counterclockwise', False)\n",
    "                    sketch_commands.append(f\"A ({x}, {y}, {alpha}, {f})\")\n",
    "                    direction = \"counterclockwise\" if f else \"clockwise\"\n",
    "                    sketch_descriptions.append(f\"{model_name} creates an arc ending at ({x}, {y}), sweeping {alpha} degrees {direction}.\")\n",
    "    \n",
    "    return ' -> '.join(sketch_commands), '\\n'.join(sketch_descriptions)\n",
    "\n",
    "def parse_extrude(entity, model_name):\n",
    "    name = entity['name']\n",
    "    extent_one = entity['extent_one']\n",
    "    extent_two = entity['extent_two']\n",
    "    operation = entity['operation']\n",
    "    \n",
    "    if 'transform' in entity:\n",
    "        transform = entity['transform']\n",
    "        theta = transform['x_axis']['x']\n",
    "        phi = transform['y_axis']['y']\n",
    "        psi = transform['z_axis']['z']\n",
    "        px = transform['origin']['x']\n",
    "        py = transform['origin']['y']\n",
    "        pz = transform['origin']['z']\n",
    "    else:\n",
    "        theta = phi = psi = 0\n",
    "        px = py = pz = 0\n",
    "    \n",
    "    s = 1 \n",
    "    e1 = extent_one['distance']['value']\n",
    "    e2 = extent_two['distance']['value']\n",
    "    b = operation\n",
    "    u = entity['extent_type']\n",
    "    \n",
    "    command = f\"E ({theta}, {phi}, {psi}, {px}, {py}, {pz}, {s}, {e1}, {e2}, {b}, {u})\"\n",
    "    description = f\"{model_name} performs an extrude operation named {name} with the following parameters:\\n\" \\\n",
    "                  f\"{model_name} sets the direction to ({theta}, {phi}, {psi}),\\n\" \\\n",
    "                  f\"{model_name} sets the origin to ({px}, {py}, {pz}),\\n\" \\\n",
    "                  f\"{model_name} sets the scale to {s},\\n\" \\\n",
    "                  f\"{model_name} sets the extent one to {e1},\\n\" \\\n",
    "                  f\"{model_name} sets the extent two to {e2},\\n\" \\\n",
    "                  f\"{model_name} sets the operation to {b},\\n\" \\\n",
    "                  f\"{model_name} sets the extent type to {u}.\"\n",
    "    \n",
    "    return command, description"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define a function to check if a page break is needed\n",
    "def check_page_break(y, c):\n",
    "    if y < 40: \n",
    "        c.showPage()\n",
    "        c.setFont(\"Helvetica\", 12)\n",
    "        return 750 \n",
    "    return y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Catalogue Initial\n",
    "\n",
    "# PDF_directory is the local storage path for generated PDF files.\n",
    "PDF_directory = \"D:\\VSCODE\\paper_code\\PDF\"\n",
    "# Build a path pattern that searches all files\n",
    "all_PDFfiles_pattern = []\n",
    "all_PDFfiles_pattern = os.path.join(PDF_directory, \"*\")\n",
    "\n",
    "# Get a list of all files in a directory\n",
    "all_PDFfiles = []\n",
    "all_PDFfiles = glob.glob(all_PDFfiles_pattern)\n",
    "\n",
    "for PDFfile in all_PDFfiles:\n",
    "    try:\n",
    "        os.remove(PDFfile)\n",
    "        print(f\"Deleted documents: {PDFfile}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error when deleting a file: {PDFfile}, error: {e}\")\n",
    "\n",
    "# Initial step file\n",
    "# Output the path to the folder next to step\n",
    "output_edges_folder_path = \"D:\\VSCODE\\paper_code\\edges_step\"\n",
    "# Build a path pattern that searches all files\n",
    "all_stepfiles_pattern = []\n",
    "all_stepfiles_pattern = os.path.join(output_edges_folder_path, \"*\")\n",
    "\n",
    "# Get a list of all files in a directory\n",
    "all_stepfiles = []\n",
    "all_stepfiles = glob.glob(all_stepfiles_pattern)\n",
    "\n",
    "for stepfile in all_stepfiles:\n",
    "    try:\n",
    "        os.remove(stepfile)\n",
    "        print(f\"Deleted documents: {stepfile}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error when deleting a file: {stepfile}, error: {e}\")\n",
    "\n",
    "# Initial stl file\n",
    "# Output the path to the folder next to step\n",
    "stl_path = 'D:\\\\VSCODE\\\\paper_code\\\\newstl'\n",
    "# Build a path pattern that searches all files\n",
    "all_stl_pattern = []\n",
    "all_stl_pattern = os.path.join(stl_path, \"*\")\n",
    "\n",
    "# Get a list of all files in a directory\n",
    "all_stlfiles = []\n",
    "all_stlfiles = glob.glob(all_stl_pattern)\n",
    "\n",
    "for stlfile in all_stlfiles:\n",
    "    try:\n",
    "        os.remove(stlfile)\n",
    "        print(f\"Deleted documents: {stlfile}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error when deleting a file: {stlfile}, error: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importing a step file\n",
    "\n",
    "# Model folder path\n",
    "folder_path = \"D:\\\\VSCODE\\\\paper_code\\\\dataset\\\\ABC_parts_210000-219999\\\\acctest\"\n",
    " # deep_data_directory is the local storage path for CAD model deepldata.\n",
    "deep_data_directory = 'D:\\\\VSCODE\\\\paper_code\\\\deepdata\\\\0021'\n",
    "\n",
    "# Iterate through all files in a folder\n",
    "for file_name in os.listdir(folder_path):\n",
    "    # Constructing full file paths\n",
    "    model_file_path = None\n",
    "    model_file_path = os.path.join(folder_path, file_name)\n",
    "\n",
    "    # Get the filename of the currently read file\n",
    "    current_file_name = []\n",
    "    first_8_chars = []\n",
    "    current_file_name = os.path.basename(model_file_path)\n",
    "    first_8_chars = current_file_name[:8]\n",
    "    \n",
    "    # Importing STEP files\n",
    "    model = None\n",
    "    model = cq.importers.importStep(model_file_path)\n",
    "\n",
    "    # Convert to stl file\n",
    "    new_stl_name = []\n",
    "    new_stl_name = first_8_chars+ \".stl\"\n",
    "    output_stl_file_path = None\n",
    "    output_stl_file_path = os.path.join(stl_path, new_stl_name)\n",
    "\n",
    "    cq.exporters.export(model, output_stl_file_path)\n",
    "    \n",
    "    shape = None\n",
    "    shape = model.val()  # Getting Shape Objects\n",
    "\n",
    "    # Get cylindrical faces and rounded edges\n",
    "    circular_edges = None\n",
    "    circular_edges = model.faces(\"%CYLINDER\").edges(\"%CIRCLE\")\n",
    "\n",
    "    # Construct a new filename starting with edges\n",
    "    new_file_name = []\n",
    "    new_file_name = \"edges_\" + first_8_chars+ \".step\"\n",
    "\n",
    "    # Construct the full output file path\n",
    "    output_edges_file_path = None\n",
    "    output_edges_file_path = os.path.join(output_edges_folder_path, new_file_name)\n",
    "\n",
    "    # Exporting processed STEP files\n",
    "    cq.exporters.export(model, output_edges_file_path)\n",
    "\n",
    "    # read step file\n",
    "    step_reader = STEPControl_Reader()\n",
    "    for file in os.listdir(output_edges_folder_path):\n",
    "        edges_file_path = None\n",
    "        edges_file_path = os.path.join(output_edges_folder_path, file)\n",
    "\n",
    "    status = []   \n",
    "    unit = None \n",
    "    status = step_reader.ReadFile(edges_file_path)\n",
    "\n",
    "    if status == 1:  # IFSelect_RetDone == 1\n",
    "        step_reader.TransferRoots()\n",
    "        unit = Interface_Static.CVal(\"xstep.cascade.unit\")\n",
    "        shape = step_reader.OneShape()\n",
    "    else:\n",
    "        raise Exception(\"Failed to read the STEP file\")\n",
    "    \n",
    "\n",
    "    \n",
    "    # Calculate the number and diameter of holes\n",
    "    circle_data = []\n",
    "    circle_count = []\n",
    "    filtered_edges = []\n",
    "    filtered_centers = []\n",
    "    circle_data, circle_count, filtered_edges, filtered_centers = analyze_holes(shape, tolerance=1e-7)\n",
    "\n",
    "    if circle_count > 0:\n",
    "        collinear_groups = None\n",
    "        collinear_groups = group_collinear_centers(filtered_centers, tolerance=1e-7)\n",
    "\n",
    "        axis_directions = []\n",
    "        parallel_count = []\n",
    "        perpendicular_count = []\n",
    "        axis_directions, parallel_count, perpendicular_count = calculate_axis_directions_and_relationships(collinear_groups)\n",
    "\n",
    "    # Calculate the number of straight and curved edges of the model\n",
    "    whole_shape = None\n",
    "    whole_shape = read_step_file(model_file_path)\n",
    "\n",
    "    straight_edge_per = []\n",
    "    curved_edge_per = []\n",
    "    straight_edge_per, curved_edge_per = classify_edges_in_shape(whole_shape)\n",
    "\n",
    "    # Computational base information\n",
    "    mesh = None\n",
    "    mesh = tm.load(output_stl_file_path)\n",
    "\n",
    "    #Extract model volume\n",
    "    Volume = []\n",
    "    Volume = mesh.volume\n",
    "    \n",
    "    #Extract model surface area\n",
    "    surface_area = []\n",
    "    surface_area = mesh.area\n",
    "\n",
    "    # Calculate the volume of the enclosing box\n",
    "    bounding_boxmesh = None\n",
    "    box_volume = []\n",
    "    bounding_boxmesh = mesh.bounding_box_oriented\n",
    "    box_volume = bounding_boxmesh.volume\n",
    "\n",
    "    # Calculating Gaussian curvature\n",
    "    gauss_curvature = []\n",
    "    variance_gauss = []\n",
    "    gauss_curvature = tm.curvature.vertex_defects(mesh)\n",
    "    variance_gauss = np.var(gauss_curvature)\n",
    "\n",
    "    mean_curvature = []\n",
    "    variance_mean = []\n",
    "    mean_curvature = mesh.integral_mean_curvature\n",
    "    variance_mean = np.var(mean_curvature)\n",
    "\n",
    "    # Determine if a plane\n",
    "    is_flat = None\n",
    "    is_flat = np.abs(gauss_curvature) < 1e-1\n",
    "    # Calculate the proportions of planes and surfaces\n",
    "    flat_ratio = []\n",
    "    curved_ratio = []\n",
    "    curved_ratio = np.sum(is_flat) / len(gauss_curvature) *100\n",
    "    flat_ratio = 100 - curved_ratio\n",
    "\n",
    "    symmetry_description = None\n",
    "    symmetry_axis = None\n",
    "    symmetry_description, symmetry_axis = determine_symmetry(mesh)\n",
    "\n",
    "    # deep data\n",
    "    new_json_name = []\n",
    "    new_json_name = first_8_chars+ \".json\"\n",
    "    json_file_path = None\n",
    "    json_file_path = os.path.join(deep_data_directory, new_json_name)\n",
    "    json_model_name = None\n",
    "    json_model_name = f\"model_{first_8_chars}\"\n",
    "    command_sequence, descriptions = parse_json_to_sequence(json_file_path, json_model_name)\n",
    "\n",
    "    # Generate PDF\n",
    "    # Generate file name\n",
    "    PDF_filename = f\"model_{first_8_chars}.pdf\"\n",
    "    \n",
    "    # Creating full file paths\n",
    "    PDF_file_path = os.path.join(PDF_directory, PDF_filename)\n",
    "    \n",
    "    # Create a Canvas object\n",
    "    c = canvas.Canvas(PDF_file_path, pagesize=letter)\n",
    "    \n",
    "    # Setting fonts and sizes\n",
    "    c.setFont(\"Helvetica\", 12)\n",
    "    # Set the initial coordinates.\n",
    "    x = 20\n",
    "    y = 730\n",
    "    page_height = letter[1]\n",
    "    \n",
    "    # Add Text\n",
    "    c.drawString(20, y, f\"The volume of the model_{first_8_chars} is {Volume:.3f} cubic {unit}.\")\n",
    "    y -= 20\n",
    "    c.drawString(20, y, f\"The surface area of the model_{first_8_chars} is {surface_area:.3f} square {unit}.\")\n",
    "    y -= 20\n",
    "    c.drawString(20, y, f\"The volume of this model_{first_8_chars} bounding box is {box_volume:.3f} cubic {unit}.\")\n",
    "    y -= 20\n",
    "    c.drawString(20, y, f\"The variance of the Gaussian curvature of this model_{first_8_chars} is {variance_gauss:.3f}.\")\n",
    "    y -= 20\n",
    "    c.drawString(20, y, f\"The variance of the Mean curvature of this model_{first_8_chars} is {variance_mean:.3f}.\")\n",
    "    y -= 20\n",
    "    c.drawString(20, y, f\"The flat plane of this model_{first_8_chars} occupies {flat_ratio:.3f}%.\")\n",
    "    y -= 20\n",
    "    c.drawString(20, y, f\"The curved surface of this model_{first_8_chars} occupies {curved_ratio:.3f}%.\")\n",
    "    y -= 20\n",
    "    # Add information about straight and curved edges\n",
    "    c.drawString(20, y, f\"The straight edge of this model_{first_8_chars} occupies {straight_edge_per:.3f}%.\")\n",
    "    y -= 20\n",
    "    y = check_page_break(y, c)\n",
    "    c.drawString(20, y, f\"The curved edge of this model_{first_8_chars} occupies {curved_edge_per:.3f}%.\")\n",
    "    y -= 20\n",
    "    y = check_page_break(y, c)\n",
    "    c.drawString(20, y, f\"{symmetry_description}\")\n",
    "    y -= 20\n",
    "    c.drawString(20, y, f\"The axis of symmetry of this model_{first_8_chars} is {symmetry_axis}.\")\n",
    "    y -= 20\n",
    "\n",
    "    # Adding information about the hole\n",
    "    for index, row in circle_data.iterrows():\n",
    "        c.drawString(20, y, f\"One of the round holes in this model_{first_8_chars} has a diameter {index + 1} of {row['Diameter']:.3f} {unit}\")\n",
    "        y -= 20\n",
    "        y = check_page_break(y, c)\n",
    "\n",
    "    c.drawString(20, y, f\"Total number of round holes of this model_{first_8_chars} is {circle_count}.\")\n",
    "    y -= 20\n",
    "\n",
    "    # Adding information about the central axis\n",
    "    if circle_count > 1:\n",
    "        c.drawString(20, y, f\"The number of all parallel holes for model_{first_8_chars} is {parallel_count}.\")\n",
    "        y -= 20\n",
    "        y = check_page_break(y, c)\n",
    "        c.drawString(20, y, f\"The number of all perpendicular holes for model_{first_8_chars} is {perpendicular_count}.\")\n",
    "        y -= 20\n",
    "        y = check_page_break(y, c)\n",
    "\n",
    "\n",
    "    # Generate deepdata information.\n",
    "    \n",
    "    lines = simpleSplit(descriptions, c._fontname, c._fontsize, letter[0] - 40)\n",
    "    for line in lines:\n",
    "        c.drawString(20, y, line)\n",
    "        y -= 20\n",
    "        y = check_page_break(y, c)\n",
    "    \n",
    "\n",
    "    c.save()\n",
    "\n",
    "   \n",
    "\n",
    "    \n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
